### ISSUE TITLE
Add more C program 

### ISSUE THREAD

**Issue by Abhay0809** [Abhay0809/C-Solution#1]

**Comment by sumanchaurasiya** [comment]
I would like to contribute.

**Comment by paras3624** [comment]
Hey! Can i contribute in this issue?

**Comment by karan-2028** [comment]
i would like to contribute on this. can you please assign me

**Comment by swosti-1603** [comment]
Hi! I would like to contribute. Can you please assign it to me?

**Comment by ROHZZZ** [comment]
he! I would like to contribute , would you please assign me?

**Comment by ashuagr** [comment]
hi please assign me this issues

**Comment by Sourabh-ks** [comment]
working  on the issue

**Comment by Sourabh-ks** [comment]
added question on Matrix Multiplication in C language
Please merge my PR and label it as "hacktoberfest" so it can be added in hacktoberfest. 
ThankYou

**Comment by 8228069354** [comment]
i want to like contribute please assign this to me.
